import UIKit
//: Structs exists in Ruby but they are not as commonly used as they are in Swift. A struct is like a class, but it is a value type. Unlike objects which are passed by reference to a pointer, structs are copied by value when they are passed around.
struct Point {
    let x: CGFloat // CoreGraphicsFloat
    let y: CGFloat
    
    // You can define initializers for structs, but they are also autogenerated for you.
}

let p = Point(x: 10, y: 10)

p.x * p.y

//: [Previous](@previous)

//: [Next](@next)
